# Game
MAX_MOVEMENT_BORDER = 290
MIN_MOVEMENT_BORDER = -290
MAX_PLACEMENT_BORDER = 250
MIN_PLACEMENT_BORDER = -250
MIN_HEADING_ANGLE = 0
MAX_HEADING_ANGLE = 360

# Sprite
SPRITE_DEFAULT_ROTATION_ANGLE = 60
SPRITE_HIT_BOX = 20

# Player
INITIAL_PLAYER_SPEED = 2
PLAYER_ROTATION_ANGLE = 45
PLAYER_ACCELERATION = 1
PLAYER_HIT_ACCELERATION_MULTIPLIER = 0.5

# Enemy
ENEMY_SPEED = 2
ENEMY_ROTATION_ANGLE = 45

# Ally
ALLY_SPEED = 2
ALLY_ROTATION_ANGLE = 60
ALLY_AVOID_BOX = 40

# Missile
MISSILE_SPEED = 20
